spring:
  application:
    name: trade-journal

  datasource:
    url: jdbc:postgresql://ep-misty-band-a87iykfw-pooler.eastus2.azure.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_kfvm1Uw9AIto
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

api:
  key: febb5121dca74bab969fbba598985f8d

cloudinary:
  cloud-name: dt8n8e3tg
  api-key: 444974451337952
  api-secret: YmvMRAw332s6-rYxXYCMHWPgyKc